
services:
  web-server:
    image: nginx:stable
    container_name: my-ubuntu-web
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - EDITOR=vim
      - PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
      - TERM=xterm-256color
      - UMASK=022
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
    stdin_open: true    # Keeps container running
    tty: true          # Allows interactive terminal
    restart: unless-stopped
    deploy: 
      resources:
        limits: 
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  adguard:
    container_name: adguard-home
    image: adguard/adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000"
      - "8082:80"
    environment:
      - EDITOR=vim
      - PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
      - TERM=xterm-256color
      - UMASK=022
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

  n8n:
    container_name: n8n
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - EDITOR=vim
      - PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
      - TERM=xterm-256color
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://192.168.1.30:5678/
      - UMASK=022
    volumes:
      - ./n8n:/home/node/.n8n
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'
        reservations:
          memory: 256M
          cpus: '0.2'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"  # HTTPS port
    environment:
      - EDITOR=vim
      - PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
      - TERM=xterm-256color
      - UMASK=022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
